apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-cache-run-3
  namespace: default
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: test-cache-pipeline
      - name: namespace
        value: default
      - name: cache
        value: always
