apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: clone-and-list-pipeline
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-source
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: Tekton
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: version
            value: "0.9"
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: https://github.com/tektoncd/pipeline.git
        - name: revision
          value: main
