apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: buildah-tekton-hub
spec:
  taskRef:
    resolver: hub
    params:
      - name: type
        value: Tekton
      - name: catalog
        value: Tekton
      - name: kind
        value: task
      - name: name
        value: buildah
      - name: version
        value: "0.6"
  params:
    - name: IMAGE
      value: my-registry/my-image:latest
  workspaces:
    - name: source
      emptyDir: {}
