apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: git-clone-artifact-hub
spec:
  taskRef:
    resolver: hub
    params:
      - name: catalog
        value: tekton-catalog-tasks
      - name: kind
        value: task
      - name: name
        value: git-clone
      - name: version
        value: "0.9.0"
  params:
    - name: url
      value: https://github.com/tektoncd/pipeline.git
    - name: revision
      value: main
  workspaces:
    - name: output
      emptyDir: {}
