# Slash Command Routing (test setup for /squash)
name: Slash Command Routing
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - name: route-land
      uses: peter-evans/slash-command-dispatch@9bdcd7914ec1b75590b790b844aa3b8eee7c683a # v5.0.2
      with:
        token: ${{ secrets.CHATOPS_TOKEN }}
        config: >
          [
            {
              "command": "squash",
              "permission": "write",
              "issue_type": "pull-request",
              "repository": "waveywaves/tekton-pipeline"
            }
          ]
